### ISSUE TITLE
Integer overflow with header_start += archive_offset when reading file with malformed header

### ISSUE THREAD

**Issue by 5225225** [zip-rs/zip#234]
Found through fuzzing.

Reproduction program (sorry for the large blob of bytes, I don't really understand the zip format enough to cut it down):

```rust
fn main() {
    let f = [0, 80, 75, 1, 2, 127, 120, 0, 3, 3, 75, 80, 232, 3, 0, 0, 0, 0, 0, 0, 3, 0, 1, 0, 7,
    0, 0, 0, 0, 65, 0, 1, 0, 0, 0, 4, 0, 0, 224, 255, 0, 255, 255, 255, 255, 255, 255, 20, 39, 221,
    221, 221, 221, 221, 221, 205, 221, 221, 221, 42, 221, 221, 221, 221, 221, 221, 221, 221, 38,
    34, 34, 219, 80, 75, 5, 6, 0, 0, 0, 0, 5, 96, 0, 1, 71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 234,
    236, 124, 221, 221, 37, 221, 221, 221, 221, 221, 129, 4, 0, 0, 221, 221, 80, 75, 1, 2, 127,
    120, 0, 4, 0, 0, 2, 127, 120, 0, 79, 75, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 0, 0, 234, 0, 0, 0, 3, 8, 4, 232, 3, 0, 0, 0, 255, 255, 255, 255, 1, 0, 0, 0, 0, 7, 0, 0,
    0, 0, 3, 0, 221, 209, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 58, 58, 42, 75,
    9, 2, 127, 120, 0, 99, 99, 99, 99, 99, 99, 94, 7, 0, 0, 0, 0, 0, 0, 213, 213, 213, 213, 213,
    213, 213, 213, 213, 7, 0, 0, 211, 211, 211, 211, 124, 236, 99, 99, 99, 94, 7, 0, 0, 0, 0, 0, 0,
    213, 213, 213, 213, 213, 213, 213, 213, 213, 7, 0, 0, 211, 211, 211, 211, 124, 236, 234, 0, 0,
    0, 3, 8, 0, 0, 0, 12, 0, 0, 0, 0, 0, 3, 0, 0, 0, 7, 0, 0, 0, 0, 0, 58, 58, 58, 42, 175, 221,
    253, 221, 221, 221, 221, 221, 80, 75, 9, 2, 127, 120, 0, 99, 99, 99, 99, 99, 99, 94, 7, 0, 0,
    0, 0, 0, 0, 213, 213, 213, 213, 213, 213, 213, 213, 213, 7, 0, 0, 211, 211, 211, 211, 124, 236,
    221, 221, 221, 221, 221, 80, 75, 9, 2, 127, 120, 0, 99, 99, 99, 99, 99, 99, 94, 7, 0, 0, 0, 0,
    0, 0, 213, 213, 213, 213, 213, 213, 213, 213, 213, 7, 0, 0, 211, 211, 211, 211, 124, 236];

    let reader = std::io::Cursor::new(&f);

    let mut archive = zip::ZipArchive::new(reader).expect("failed to make archive");

    for i in 0..archive.len() {
        let _file = archive.by_index(i);
    }
}
```

backtrace:

```
thread 'main' panicked at 'attempt to add with overflow', /home/jess/src/zip/src/read.rs:591:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4ae0a8e413a67b9f6c38f09b24f6179e98c1ba25/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/4ae0a8e413a67b9f6c38f09b24f6179e98c1ba25/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/4ae0a8e413a67b9f6c38f09b24f6179e98c1ba25/library/core/src/panicking.rs:50:5
   3: zip::read::central_header_to_zip_file
             at /home/jess/src/zip/src/read.rs:591:5
   4: zip::read::ZipArchive<R>::new
             at /home/jess/src/zip/src/read.rs:334:24
   5: scratchGaVSRuLnQ::main
             at ./src/main.rs:22:23
   6: core::ops::function::FnOnce::call_once
             at /home/jess/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by 5225225** [comment]
It was just

```rust
#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    let reader = std::io::Cursor::new(data);
    let mut archive = if let Ok(x) = zip::ZipArchive::new(reader) {
        x
    } else {
        return;
    };

    for i in 0..archive.len() {
        use std::io::prelude::*;
        if let Ok(file) = archive.by_index(i) {
            for b in file.bytes() {
                if b.is_err() {
                    return;
                }
            }
        }
    }
});
```

Pretty basic, but also quite similar to the harness they showed.

**Comment by Plecra** [comment]
Ace, thankyou :)

**Comment by Plecra** [comment]
Ace, thankyou :)

**Comment by zamazan4ik** [comment]
@5225225 Could you please check that the issue is still reproducible with the latest `zip-rs` version from the `master` branch? Thanks!

**Comment by zamazan4ik** [comment]
Confirmed that the issue still exists in the library. Working on the fix.

**Comment by zamazan4ik** [comment]
Fix is here: https://github.com/zip-rs/zip/pull/259

**Comment by zamazan4ik** [comment]
https://github.com/zip-rs/zip/pull/259 is merged so I think the issue can be closed.
